sudo: required

services:
  - docker

install: true

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  # building image and testing it
  - docker-compose up sut

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    # tagging the built image with correct name 
    docker tag dockercapybarawebkitchromedriver_chromedriver:latest $NAME:$VERSION;
    docker push $NAME:$VERSION;
    fi
