sudo: required

services:
  - docker

install: true

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - docker-compose version
  - docker-compose run sut

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag dockercapybarawebkitchromedriver_chromedriver:latest $NAME:$VERSION && docker push $NAME:$VERSION;
    fi
